### ISSUE TITLE
There is no "Usage Stats" option in the Settings of my Android Emulator.

### ISSUE THREAD

**Issue by yixiaoliuw** [WednesdayWolf/reef#3]
Following provided instructions in the top-level directory, I was not able to properly set up an Android Emulator from the downloaded "vs_emulatorsetup.exe" file. By always clicking "next" after opening the downloaded file I got a program "Xamarin Profiler" opened and running. However, I am not sure how to properly set up an Android Emulator. I attempted to search for solutions in the provided troubleshoot link but it was not helpful. I had Android Device Manager installed on my machine (Mac OS) from Android Studio and Visual Studio automatically detects and uses Android Device Manager. After creating an Android Emulator with SDK 28 from the Android Device Manager and set it running, I was not able to locate the "Usage Stats" option in the Settings program on the Android Emulator for enabling Usage Stats for reef.android.

Firstly, the Android Emulator Settings screen:
<img width="411" alt="Screen Shot 2021-05-23 at 11 28 06 AM" src="https://user-images.githubusercontent.com/56842311/119272373-68b5fb00-bbba-11eb-9809-fa4403fe64b5.png">

Secondly, the result from searching "Usage Stats":
<img width="411" alt="Screen Shot 2021-05-23 at 11 28 15 AM" src="https://user-images.githubusercontent.com/56842311/119272394-7bc8cb00-bbba-11eb-83a0-3df6612cc889.png">

I also attempted to look for "Usage Stats" option in the Settings but I did not locate it.

**Comment by ehusted01** [comment]
Sorry about that, could you try searching for "Usage data access" and let me know if you have any luck?

**Comment by yixiaoliuw** [comment]
There is no "Usage data access", but I think the "Usage access" on my device might be the one you are looking for.

**Comment by ehusted01** [comment]
@yixiaoliuw Yup, I think that is probably it. It might be named differently depending on Android version
