### ISSUE TITLE
Hyper V not supported on Windows 10 Home OS system. Blocking installation of Microsoft Android Emulator

### ISSUE THREAD

**Issue by arik-shurygin** [WednesdayWolf/reef#5]
As stated above the used emulator requires a BIOS application titled "Hyper V". After following the link to the emulator and downloading the installer I was met with this message:
![image](https://user-images.githubusercontent.com/39861882/119403008-98383680-bc92-11eb-809e-a2d3ab83c10d.png)

Here is another link which also mentions Hyper V dependencies on certain OS systems. https://social.technet.microsoft.com/Forums/en-US/c3d8faaa-2e5a-4cfb-a681-9dfdf8bc5310/cant-install-hyperv-on-windows-10-version-1001024016384-feature-name-microsofthyperv-is?forum=win10itprovirt

https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2015/cross-platform/system-requirements-for-the-visual-studio-emulator-for-android?view=vs-2015&redirectedfrom=MSDN

While I can tell there is a lot of effort on making clean and easy to read instructions I was not able to proceed past this step. I attempted to download other emulators but without familiarity with your code it made it difficult to simply plug into this existing project. 

I would strongly suggest trying to get this project to work with a different emulator and offering alternative instructions to download that for any users who are on Windows 10 home/Mobile/Mobile Enterprise OS systems. I love the idea of this project and would love to use it on final release!

**Comment by WednesdayWolf** [comment]
It's not possible to run an android emulator without a Hyper-V on Windows, so deploying with an emulator is not possible on Windows 10 home/mobile/mobile enterprise.

Do you have access to a physical Android device or macOS system?
