### ISSUE TITLE
Hyper-V issue while installing the VS emulator

### ISSUE THREAD

**Issue by praneshr2000** [WednesdayWolf/reef#6]
I was not able to get VS emulator running on my computer because Hyper-V is not supported on my machine. For reference, I am running on Windows 10 Home. Below is the screenshot of the problem I am facing.

![image](https://user-images.githubusercontent.com/65135230/119488224-5a5b1100-bd6b-11eb-8ebe-96fc4c61a44c.png)

**Comment by WednesdayWolf** [comment]
It's not possible to run an android emulator without a Hyper-V on Windows, so deploying with an emulator is not possible on Windows 10 home/mobile/mobile enterprise.

Do you have access to a physical Android device or macOS system?
