### ISSUE TITLE
Unable to run "Emulator for Android Apps" with "Visual Studio 2019"

### ISSUE THREAD

**Issue by bhl00** [WednesdayWolf/reef#7]
Following the provided instructions from the top-level directory, I installed Visual Studio 2019 from https://visualstudio.microsoft.com/downloads/ and the Emulator for Android Apps from https://visualstudio.microsoft.com/vs/msft-android-emulator/. Note that I am currently using OS Microsoft Windows 10 Pro on Version 10.0.18363 Build 18363. I attempted to run the Android Emulator as seen in the following screenshots but am unable to do so with the error described in the final screenshot.

Run Screen:
![image](https://user-images.githubusercontent.com/18492719/119595697-cbfa8580-bd92-11eb-9353-2c3bf837670d.png)

Emulator Screen (stuck):
![image](https://user-images.githubusercontent.com/18492719/119595742-e03e8280-bd92-11eb-9905-8d114fd311cf.png)

Error Screen:
![image](https://user-images.githubusercontent.com/18492719/119595778-eaf91780-bd92-11eb-9b04-517c88db2d9d.png)

Note that Visual Studio Emulator for Android is no longer supported Visual Studio 2017 and 2019 as described in https://docs.microsoft.com/en-us/visualstudio/cross-platform/visual-studio-emulator-for-android?view=vs-2017 and instead Google Android emulators are now being recommended.

**Comment by WednesdayWolf** [comment]
Could you verify that you have Hyper-V enabled on your machine?

**Comment by WednesdayWolf** [comment]
Ah I see the error now, documentation pointed you to the wrong place. Fixed now.
