### ISSUE TITLE
Unable to build the project in "Visual Studio 2019"

### ISSUE THREAD

**Issue by bhl00** [WednesdayWolf/reef#8]
Following the provided instructions from the top-level directory, I installed Visual Studio 2019 from https://visualstudio.microsoft.com/downloads/. I am currently unable to build and run tests of the project due to the following error described in the screenshot. 

![image](https://user-images.githubusercontent.com/18492719/119596723-935bab80-bd94-11eb-9dcd-5073470890a9.png)

It seems that the current version of Visual Studio does not support the project. Perhaps a different version of Visual Studio was used during the development process, and such a version could possibly be reflected in the instructions to fix the issue.

**Comment by WednesdayWolf** [comment]
You've currently selected `reef.testing` as your build project. As per the documentation, you should have `reef.android` as your build project.
